//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yorot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yorot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///    &lt;Name&gt;English (United Kingdom)&lt;/Name&gt;
        ///    &lt;Author&gt;Haltroy&lt;/Author&gt;
        ///    &lt;CodeName&gt;com.haltroy.english-gb&lt;/CodeName&gt;
        ///    &lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///    &lt;Version&gt;1&lt;/Version&gt;
        ///    &lt;HTUPDATE&gt;&lt;/HTUPDATE&gt;
        ///  &lt;/Group&gt;
        ///  &lt;Group Name=&quot;Settings&quot;&gt;
        ///    &lt;Translate ID=&quot;&quot; Text=&quot;&quot; /&gt;
        ///  &lt;/Group&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string English_GB {
            get {
                return ResourceManager.GetString("English_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///    &lt;Name&gt;English (United States)&lt;/Name&gt;
        ///    &lt;Author&gt;Haltroy&lt;/Author&gt;
        ///    &lt;CodeName&gt;com.haltroy.english-us&lt;/CodeName&gt;
        ///    &lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///    &lt;Version&gt;1&lt;/Version&gt;
        ///    &lt;HTUPDATE&gt;&lt;/HTUPDATE&gt;
        ///  &lt;/Group&gt;
        ///  &lt;Group Name=&quot;Settings&quot;&gt;
        ///    &lt;Translate ID=&quot;&quot; Text=&quot;&quot; /&gt;
        ///  &lt;/Group&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string English_US {
            get {
                return ResourceManager.GetString("English_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///    &lt;Name&gt;Türkçe&lt;/Name&gt;
        ///    &lt;Author&gt;Haltroy&lt;/Author&gt;
        ///    &lt;CodeName&gt;com.haltroy.turkish&lt;/CodeName&gt;
        ///    &lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///    &lt;Version&gt;1&lt;/Version&gt;
        ///    &lt;HTUPDATE&gt;&lt;/HTUPDATE&gt;
        ///  &lt;/Group&gt;
        ///  &lt;Group Name=&quot;Settings&quot;&gt;
        ///    &lt;Translate ID=&quot;&quot; Text=&quot;&quot; /&gt;
        ///  &lt;/Group&gt;
        ///&lt;/root&gt;
        ///.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
    }
}
