//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yorot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yorot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon_settings {
            get {
                object obj = ResourceManager.GetObject("addon-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_b {
            get {
                object obj = ResourceManager.GetObject("back-b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_w {
            get {
                object obj = ResourceManager.GetObject("back-w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calc {
            get {
                object obj = ResourceManager.GetObject("calc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap colman {
            get {
                object obj = ResourceManager.GetObject("colman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap console {
            get {
                object obj = ResourceManager.GetObject("console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customization {
            get {
                object obj = ResourceManager.GetObject("customization", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap default_pofile_pic {
            get {
                object obj = ResourceManager.GetObject("default-pofile-pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_and_history {
            get {
                object obj = ResourceManager.GetObject("download-and-history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///    &lt;Name&gt;English (United Kingdom)&lt;/Name&gt;
        ///    &lt;Author&gt;Haltroy&lt;/Author&gt;
        ///    &lt;CodeName&gt;com.haltroy.english-gb&lt;/CodeName&gt;
        ///    &lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///    &lt;Version&gt;1&lt;/Version&gt;
        ///    &lt;HTUPDATE&gt;&lt;/HTUPDATE&gt;
        ///  &lt;/Group&gt;
        ///  &lt;Group Name=&quot;Win32&quot;&gt;
        ///    &lt;Group Name=&quot;DefaultApps&quot;&gt;
        ///      &lt;Translation ID=&quot;Settings&quot; Text =&quot;Settings&quot; /&gt;
        ///      &lt;Translation ID=&quot;Yopad&quot; Text =&quot;Yopad&quot; /&gt;
        ///      &lt;Translation ID=&quot;Calendar&quot; Text =&quot;Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_GB {
            get {
                return ResourceManager.GetString("English_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///    &lt;Name&gt;English (United States)&lt;/Name&gt;
        ///    &lt;Author&gt;Haltroy&lt;/Author&gt;
        ///    &lt;CodeName&gt;com.haltroy.english-gb&lt;/CodeName&gt;
        ///    &lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///    &lt;Version&gt;1&lt;/Version&gt;
        ///    &lt;HTUPDATE&gt;&lt;/HTUPDATE&gt;
        ///  &lt;/Group&gt;
        ///  &lt;Group Name=&quot;Win32&quot;&gt;
        ///    &lt;Group Name=&quot;DefaultApps&quot;&gt;
        ///      &lt;Translation ID=&quot;Settings&quot; Text =&quot;Settings&quot; /&gt;
        ///      &lt;Translation ID=&quot;Yopad&quot; Text =&quot;Yopad&quot; /&gt;
        ///      &lt;Translation ID=&quot;Calendar&quot; Text =&quot;Cal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_US {
            get {
                return ResourceManager.GetString("English_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileman {
            get {
                object obj = ResourceManager.GetObject("fileman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_b {
            get {
                object obj = ResourceManager.GetObject("forward-b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_w {
            get {
                object obj = ResourceManager.GetObject("forward-w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap general_settings {
            get {
                object obj = ResourceManager.GetObject("general-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hamburger {
            get {
                object obj = ResourceManager.GetObject("hamburger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hamburger_w {
            get {
                object obj = ResourceManager.GetObject("hamburger-w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;style&gt;
        ///.yorotMap {
        ///height: 100%;
        ///width: 100%;
        ///}
        ///svg{-ms-touch-action:none;touch-action:none}image,text,.jsvmap-zoomin,.jsvmap-zoomout{-ms-user-select:none;user-select:none}.jsvmap-container{-ms-touch-action:none;touch-action:none;position:relative;overflow:hidden;height:100%;width:100%}.jsvmap-tooltip{border-radius:3px;background-color:#373f52;font-family:sans-serif,Verdana;font-size:smaller;box-shadow:1px 2px 12px rgba(0,0,0,.2);padding:3px 5px;position:absolute;display:none; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///   &lt;!-- YOROT WORLD MAP CONFIG FILE
        ///   This file includes details of the countries as the default language, date and time format and CEF locale.
        ///   End user cannot edit this file.
        ///   
        ///   NOTE: Use &quot;com.haltroy.english&quot; language if that country&apos;s default language is not added and use &quot;en_US&quot; locale if that&apos;s also
        ///   not present..
        ///   --&gt;
        ///   &lt;Countries&gt;
        ///     // TODO: Add Countrly-specific color to map and here. Also add locales.
        ///     &lt;Country Name=&quot;US&quot; MapColor=&quot;#05F245&quot; Text=&quot;United States&quot; L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapConfig {
            get {
                return ResourceManager.GetString("MapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mute {
            get {
                object obj = ResourceManager.GetObject("mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notepad {
            get {
                object obj = ResourceManager.GetObject("notepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap profiles {
            get {
                object obj = ResourceManager.GetObject("profiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap security_settings {
            get {
                object obj = ResourceManager.GetObject("security-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spacepass {
            get {
                object obj = ResourceManager.GetObject("spacepass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap store {
            get {
                object obj = ResourceManager.GetObject("store", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash_w {
            get {
                object obj = ResourceManager.GetObject("trash-w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///    &lt;Name&gt;Türkçe&lt;/Name&gt;
        ///    &lt;Author&gt;Haltroy&lt;/Author&gt;
        ///    &lt;CodeName&gt;com.haltroy.turkish&lt;/CodeName&gt;
        ///    &lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///    &lt;Version&gt;1&lt;/Version&gt;
        ///    &lt;HTUPDATE&gt;&lt;/HTUPDATE&gt;
        ///  &lt;/Group&gt;
        ///  &lt;Group Name=&quot;Win32&quot;&gt;
        ///    &lt;Group Name=&quot;DefaultApps&quot;&gt;
        ///      &lt;Translation ID=&quot;Settings&quot; Text =&quot;Ayarlar&quot; /&gt;
        ///      &lt;Translation ID=&quot;Yopad&quot; Text =&quot;Yopad&quot; /&gt;
        ///      &lt;Translation ID=&quot;Calendar&quot; Text =&quot;Takvim&quot; /&gt;
        ///      &lt;Trans [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unmute {
            get {
                object obj = ResourceManager.GetObject("unmute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_and_about {
            get {
                object obj = ResourceManager.GetObject("update_and_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wmap_backend {
            get {
                object obj = ResourceManager.GetObject("wmap-backend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wmap_front {
            get {
                object obj = ResourceManager.GetObject("wmap-front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yopad {
            get {
                object obj = ResourceManager.GetObject("yopad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yorot {
            get {
                object obj = ResourceManager.GetObject("Yorot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///&lt;title&gt;[WIP] §PAGETITLE§&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;§PAGETITLE§&lt;/h1&gt;
        ///&lt;a&gt;TODO: Embed and add all required legal information as a expandable item list.&lt;a&gt;
        ///&lt;h2 href=&quot;https://www.flaticon.com/authors/freepik&quot;&gt;§FREEPIK§&lt;/h2&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string yorot_licenses {
            get {
                return ResourceManager.GetString("yorot_licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotDark {
            get {
                object obj = ResourceManager.GetObject("YorotDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotDeepBlue {
            get {
                object obj = ResourceManager.GetObject("YorotDeepBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotLight {
            get {
                object obj = ResourceManager.GetObject("YorotLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotRazor {
            get {
                object obj = ResourceManager.GetObject("YorotRazor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotShadow {
            get {
                object obj = ResourceManager.GetObject("YorotShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotStone {
            get {
                object obj = ResourceManager.GetObject("YorotStone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
